### ISSUE TITLE
How to run a  server inside the docker image

### ISSUE THREAD

**Issue by nimish1512** [mateoguzman/openvino-docker#10]
I want to run a Http server that will serve the openvino models. However, I don't want to use -it during running the container. I have to use -d so that the container runs in background and listens for requests. How should I go about achieving this?

**Comment by mateoguzman** [comment]
Sorry for the late reply.  Do you still have this doubt? 

Depending on the technology you want to use, you could create your own Dockerfile that uses the openvino built image (see the sample-app/Dockerfile) and add your HTTP server components and change the 'CMD' command with the command to run your server. Eg

```
CMD [ "node", "server.js" ]
```

Then you would be able to run the docker container with -d, your server will be up and running and you should be able to handle the request, use the different models.

**Comment by nimish1512** [comment]
Perfect! Thanks
