### ISSUE TITLE
/bin/sh: 1: cd: can't cd to /openvino/l_openvino_toolkit*

### ISSUE THREAD

**Issue by kclim2** [mateoguzman/openvino-docker#6]
Step 6/13 : RUN cd /openvino/l_openvino_toolkit* &&     ./install_cv_sdk_dependencies.sh
 ---> Running in 5e47998b297c
/bin/sh: 1: cd: can't cd to /openvino/l_openvino_toolkit*
The command '/bin/sh -c cd /openvino/l_openvino_toolkit* &&     ./install_cv_sdk_dependencies.sh' returned a non-zero code: 2

anything wrong?

**Comment by spitfire88** [comment]
Selectively undoing this commit should fix it:
https://github.com/mateoguzman/openvino-docker/commit/28e46bf1f0ad428243442fb4f7b846a476ddc15d

Just guessing here but does docker not allow creating directories under root "/" that are not called "app"? Either that or it automatically adds permissions to "/app".

**Comment by mateoguzman** [comment]
Please check that you have downloaded and extracted the OpenVINO installer package.

The folder openvino is not created in the following command when there is no folder named l_openvino_toolkit* , so then you cannot cd into it.

ADD l_openvino_toolkit* /openvino/
